#!/bin/sh
if [ -z "$WORKSPACE" ]; then echo "environment WORKSPACE is not set";exit 1;fi
if [ $# -eq 0 ]; then echo -e "usage:\n   $(basename "$0") <project> [user note]\nwhere project is a github repository in $WORKSPACE";exit 2;fi

TS="$(date +%Y-%m-%d--%H-%M)--$2" &&
echo " * tagging project '$1' with '$TS'"
cd $WORKSPACE/$1 &&
git remote set-url origin git@github.com:calint/$1.git &&
git add . &&
git commit -m "."
git push --all &&
git tag $TS &&
git push --tags &&
echo " * done"
